### ISSUE TITLE
Code blocks not styled correctly

### ISSUE THREAD

**Issue by fmalcher** [fmalcher/md2multihtml#12]
Code blocks surrounded by three backticks ``` are not displayed correctly, see screenshot below.
They need to be block elements, not inline.

Those blocks can be recognised by their structure:

```html
<p>
  <code>...</code>
</p>
```

while inline code looks like

```html
<p>
  lorem ipsum
  <code>...</code>
  foo bar
</p>
```

---------

![bildschirmfoto 2017-01-12 um 00 50 25](https://cloud.githubusercontent.com/assets/1683147/21871403/293d4766-d862-11e6-9c51-aaeb432c985b.png)

**Comment by fmalcher** [comment]
I think that's what the style definition for `pre` is for:

```css
pre {
    margin-top: 0;
    margin-bottom: 0;
    font: 12px Consolas, "Liberation Mono", Menlo, Courier, monospace;
}
```
(from `markdown.css`)
